services:
  nats:
    image: nats:alpine
    container_name: nats
    expose:
      - 4222
      - 6222
    ports:
      - 8222:8222
      - 4222:4222
      - 6222:6222
    volumes:
      - ./.nats-data:/data
    deploy:
      resources:
        limits:
          cpus: "0.2"
          memory: 0.25g
        reservations:
          cpus: "0.2"
          memory: 0.25g
