apiVersion: apps/v1
kind: Deployment
metadata:
  name: workspace-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: workspace
  template:
    metadata:
      labels:
        app: workspace
    spec:
      containers:
        - name: workspace
          image: hideregistry.azurecr.io/hide-server-workspace:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          env:
            - name: NODE_ENV
              value: production
            - name: SERVICE_PORT
              value: "80"
            - name: RMQ_URL
              value: "amqp://rabbitmq:5672"
            - name: NATS_URL
              value: "nats://nats:4222"
            - name: REDIS_HOST
              value: redis
            - name: REDIS_PORT
              value: "6379"
            - name: POSTGRES_HOST
              value: postgres
            - name: POSTGRES_PORT
              value: "5432"
            - name: POSTGRES_USER
              value: admin
            - name: POSTGRES_DB
              value: workspacedb
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: hide-secrets
                  key: POSTGRES_PASSWORD
            - name: WORKSPACE_SERVICE_SECRET
              valueFrom:
                secretKeyRef:
                  name: hide-secrets
                  key: WORKSPACE_SERVICE_SECRET
          resources:
            limits:
              cpu: 350m
              memory: 350M
            requests:
              cpu: 350m
              memory: 350M
      imagePullSecrets:
        - name: acr-secret
