apiVersion: apps/v1
kind: Deployment
metadata:
  name: workspace-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: workspace
  template:
    metadata:
      labels:
        app: workspace
    spec:
      containers:
        - name: workspace
          image: hideregistry.azurecr.io/hide-server-workspace:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          env:
            - name: NODE_ENV
              value: production
            - name: SERVICE_PORT
              value: "80"
            - name: RMQ_URL
              value: "amqp://rabbitmq:5672"
            - name: NATS_URL
              value: "nats://nats:4222"
            - name: REDIS_HOST
              value: redis
            - name: REDIS_PORT
              value: "6379"
            - name: POSTGRES_HOST
              value: postgres
            - name: POSTGRES_PORT
              value: "5432"
            - name: POSTGRES_USER
              value: admin
            - name: POSTGRES_DB
              value: workspacedb
            - name: FIREBASE_APP_ID
              value: "hide-43a4b"
            - name: WORKSPACE_CREATION_LIMIT_GUEST
              value: "1"
            - name: WORKSPACE_CREATION_LIMIT_NON_GUEST
              value: "2"
            - name: ADMIN_EMAIL
              value: "personal@saurabhagat.me"
            - name: WORKSPACE_CPU_REQUEST
              value: "200"
            - name: "IDLE_THRESHOLD_CPU"
              value: "350"
            - name: "ACCESS_CODE_EXPIRY_DAYS"
              value: "5"
            - name: FIREBASE_KEY_BASE64
              valueFrom:
                secretKeyRef:
                  name: hide-secrets
                  key: FIREBASE_KEY_BASE64
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: hide-secrets
                  key: POSTGRES_PASSWORD
            - name: WORKSPACE_SERVICE_SECRET
              valueFrom:
                secretKeyRef:
                  name: hide-secrets
                  key: WORKSPACE_SERVICE_SECRET
            - name: AZURE_COMM_EMAIL_CONNECTION
              valueFrom:
                secretKeyRef:
                  name: hide-secrets
                  key: AZURE_COMM_EMAIL_CONNECTION
            - name: AZURE_CS_SMTP_SECRET
              valueFrom:
                secretKeyRef:
                  name: hide-secrets
                  key: AZURE_CS_SMTP_SECRET
            - name: AZURE_COMM_EMAIL_USERNAME
              valueFrom:
                secretKeyRef:
                  name: hide-secrets
                  key: AZURE_COMM_EMAIL_USERNAME
          readinessProbe:
            httpGet:
              path: /api/health
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 5
            timeoutSeconds: 5
            failureThreshold: 3
          resources:
            limits:
              cpu: 150m
              memory: 200Mi
            requests:
              cpu: 150m
              memory: 200Mi
      imagePullSecrets:
        - name: acr-secret
