networks:
  hide-network:
    driver: bridge

services:
  service-registry:
    container_name: service-registry
    hostname: service-registry
    extends:
      file: ./service-registry/docker-compose.dev.yml
      service: service-registry
    networks:
      - hide-network
  gateway:
    container_name: gateway
    hostname: gateway
    depends_on:
      service-registry:
        condition: service_healthy
    extends:
      file: ./gateway/docker-compose.dev.yml
      service: gateway
    networks:
      - hide-network
  user:
    container_name: user
    hostname: user
    depends_on:
      service-registry:
        condition: service_healthy
      redis:
        condition: service_started
    extends:
      file: ./user/docker-compose.dev.yml
      service: user
    networks:
      - hide-network
  workspace:
    container_name: workspace
    hostname: workspace
    depends_on:
      service-registry:
        condition: service_healthy
      postgres:
        condition: service_started
    extends:
      file: ./workspace/docker-compose.dev.yml
      service: workspace
    networks:
      - hide-network
  auth:
    container_name: auth
    hostname: auth
    depends_on:
      service-registry:
        condition: service_healthy
    extends:
      file: ./auth/docker-compose.dev.yml
      service: auth
    networks:
      - hide-network
  postgres:
    image: postgres:alpine
    container_name: postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASS}
      POSTGRES_DB: workspacedb
    ports:
      - "5432:5432"
    env_file:
      - ./.env
    volumes:
      - ./.postgres-data:/var/lib/postgresql/data
    networks:
      - hide-network
  adminer:
    image: adminer
    container_name: adminer
    restart: unless-stopped
    ports:
      - 8087:8080
    networks:
      - hide-network
  typesense:
    container_name: typesense
    image: typesense/typesense:28.0
    restart: on-failure
    ports:
      - "8108:8108"
    volumes:
      - ./.typesense-data:/data
    command: '--data-dir /data --api-key=test --enable-cors'
    networks:
      - hide-network
  redis:
    image: redis:alpine
    container_name: redis
    restart: on-failure
    ports:
      - "6379:6379"
    networks:
      - hide-network
  rabbitmq:
    image: rabbitmq:management-alpine
    container_name: rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - ./.rabbitmq-data:/var/lib/rabbitmq
    networks:
      - hide-network
