networks:
  hide-network:
    driver: bridge

services:
  service-registry:
    container_name: service-registry
    hostname: service-registry
    extends:
      file: ./service-registry/docker-compose.dev.yml
      service: service-registry
    networks:
      - hide-network
  gateway:
    container_name: gateway
    hostname: gateway
    depends_on:
      service-registry:
        condition: service_healthy
    extends:
      file: ./gateway/docker-compose.dev.yml
      service: gateway
    networks:
      - hide-network
  user:
    container_name: user
    hostname: user
    depends_on:
      service-registry:
        condition: service_healthy
    extends:
      file: ./user/docker-compose.dev.yml
      service: user
    networks:
      - hide-network
  auth:
    container_name: auth
    hostname: auth
    depends_on:
      service-registry:
        condition: service_healthy
    extends:
      file: ./auth/docker-compose.dev.yml
      service: auth
    networks:
      - hide-network
