networks:
  hide-network:
    driver: bridge

services:
  gateway:
    container_name: gateway
    hostname: gateway
    depends_on:
      redis:
        condition: service_started
      rabbitmq:
        condition: service_started
    extends:
      file: ./gateway/docker-compose.dev.yml
      service: gateway
    networks:
      - hide-network
  user:
    container_name: user
    hostname: user
    depends_on:
      redis:
        condition: service_started
    extends:
      file: ./user/docker-compose.dev.yml
      service: user
    networks:
      - hide-network
  notification:
    container_name: notification
    hostname: notification
    depends_on:
      redis:
        condition: service_started
      rabbitmq:
        condition: service_started
    extends:
      file: ./notification/docker-compose.dev.yml
      service: notification
    networks:
      - hide-network
  workspace:
    container_name: workspace
    hostname: workspace
    depends_on:
      postgres:
        condition: service_started
      rabbitmq:
        condition: service_started
    extends:
      file: ./workspace/docker-compose.dev.yml
      service: workspace
    networks:
      - hide-network
  auth:
    container_name: auth
    hostname: auth
    extends:
      file: ./auth/docker-compose.dev.yml
      service: auth
    networks:
      - hide-network
  provisioner:
    container_name: provisioner
    hostname: provisioner
    extends:
      file: ./provisioner/docker-compose.dev.yml
      service: provisioner
    networks:
      - hide-network
  postgres:
    extends:
      file: ./postgres/docker-compose.dev.yml
      service: postgres
    networks:
      - hide-network
  adminer:
    image: adminer
    container_name: adminer
    ports:
      - 8087:8080
    networks:
      - hide-network
  typesense:
    extends:
      file: ./typesense/docker-compose.dev.yml
      service: typesense
    networks:
      - hide-network
  redis:
    extends:
      file: ./redis/docker-compose.dev.yml
      service: redis
    networks:
      - hide-network
  rabbitmq:
    extends:
      file: ./rmq/docker-compose.dev.yml
      service: rabbitmq
    networks:
      - hide-network
