apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ./k8s/ingress.yml
  - ./k8s/clusterissuer.yml
  - ./rabbitmq/k8s/deployment.yml
  - ./rabbitmq/k8s/service.yml
  - ./rabbitmq/k8s/pvc.yml
  - ./postgres/k8s/deployment.yml
  - ./postgres/k8s/service.yml
  - ./postgres/k8s/pvc.yml
  - ./redis/k8s/deployment.yml
  - ./redis/k8s/service.yml
  - ./gateway/k8s/deployment.yml
  - ./gateway/k8s/service.yml
  - ./auth/k8s/deployment.yml
  - ./auth/k8s/service.yml
  - ./notification/k8s/deployment.yml
  - ./notification/k8s/service.yml
  - ./workspace/k8s/deployment.yml
  - ./workspace/k8s/service.yml
  - ./provisioner/k8s/deployment.yml
  - ./provisioner/k8s/service.yml
