FROM node:22-alpine AS base
RUN apk add jq
WORKDIR /app

FROM base AS development
COPY gateway ./gateway
COPY libs ./libs
RUN cd ./gateway && npm ci
RUN for dir in $(jq ".references[].path" ./gateway/tsconfig.json); do \
  (cd "${dir:2:-1}" && npm ci); \
  done
CMD ["/bin/sh", "-c", "cd gateway && npm run start:dev"]

FROM base AS build
COPY gateway ./gateway
COPY libs ./libs
RUN cd ./gateway && npm ci
RUN for dir in $(jq ".references[].path" ./gateway/tsconfig.json); do \
  (cd "${dir:2:-1}" && npm ci); \
  done
RUN npm run build --prefix gateway

FROM base AS production
COPY --from=build /app/gateway/dist ./gateway/dist
COPY --from=build /app/gateway/package.json ./gateway/package.json
COPY --from=build /app/gateway/package-lock.json ./gateway/package-lock.json
COPY --from=build /app/gateway/node_modules ./gateway/node_modules
COPY --from=build /app/libs ./libs
CMD ["/bin/sh", "-c", "cd gateway && npm run start:prod"]

EXPOSE 80