services:
  gateway:
    ports:
      - 3001:80
    build:
      context: ../
      dockerfile: gateway/dockerfile
      target: development
    image: hide-server-gateway
    volumes:
      - .:/app/gateway
      - /app/gateway/node_modules
    environment:
      - NODE_ENV=development
      - SERVICE_PORT=80
      - RMQ_URL=amqp://rabbitmq:5672
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - CORS_ORIGIN=*
      - FIREBASE_EMULATION=true
      - FIREBASE_AUTH_EMULATOR_HOST=host.docker.internal:9099
      - FIRESTORE_EMULATOR_HOST=host.docker.internal:8085
      - FIREBASE_STORAGE_EMULATOR_HOST=host.docker.internal:9199
      - FIREBASE_APP_ID=hide-43a4b
      - JWT_PUBLIC_KEY=test
    command: [ "/bin/sh", "-c", "cd gateway && npm run start:dev" ]
