services:
  gateway:
    extends:
      file: docker-compose.yml
      service: gateway
    build:
      context: .
      target: production
    environment:
      - EUREKA_HOST=host.docker.internal
      - EUREKA_PORT=8761
      - SERVICE_NAME=API-GATEWAY
      - SERVICE_PORT=3001
    command: node dist/main.js
