services:
  gateway:
    extends:
      file: docker-compose.yml
      service: gateway
    build:
      context: ../
      dockerfile: gateway/dockerfile
      target: development
    volumes:
      - .:/app/gateway
      - /app/gateway/node_modules
    environment:
      - NODE_ENV=development
      - EUREKA_HOST=service-registry
      - EUREKA_PORT=8761
      - SERVICE_NAME=API-GATEWAY
      - SERVICE_PORT=3001
    command: [ "/bin/sh", "-c", "cd gateway && npm run start:dev" ]
