apiVersion: v1
kind: PersistentVolume
metadata:
  name: typesense-pv
spec:
  storageClassName: local-path
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /data/typesense
    type: DirectoryOrCreate
  persistentVolumeReclaimPolicy: Retain
