apiVersion: v1
kind: ConfigMap
metadata:
  name: alloy-config
  namespace: default
data:
  config.alloy: |
    logging {
      level  = "info"
      format = "logfmt"
    }

    file.match "k8s-logs" {
      path_targets = ["/var/log/containers/*.log"]
    }

    discovery.relabel "k8s-filter" {
      targets = file.match.k8s-logs.targets

      rule {
        source_labels = ["__meta_kubernetes_namespace"]
        regex         = "default"
        action        = "keep"
      }

      rule {
        source_labels = ["__meta_kubernetes_pod_label_logging"]
        regex         = "off"
        action        = "drop"
      }

      rule {
        source_labels = ["__meta_kubernetes_pod_label_app"]
        target_label  = "service_name"
        action        = "replace"
      }

      rule {
        source_labels = ["__meta_kubernetes_namespace"]
        target_label  = "namespace"
        action        = "replace"
      }
      rule {
        source_labels = ["__meta_kubernetes_pod_name"]
        target_label  = "pod"
        action        = "replace"
      }
      rule {
        source_labels = ["__meta_kubernetes_container_name"]
        target_label  = "container"
        action        = "replace"
      }
    }

    file.source "k8s" {
      targets    = discovery.relabel.k8s-filter.output
      forward_to = [loki.process.k8s.receiver]
    }

    loki.process "k8s" {
      forward_to = [loki.write.local.receiver]

      stage.docker {}
    }

    loki.write "local" {
      endpoint {
        url = "http://loki:3100/loki/api/v1/push"
      }
    }
