apiVersion: v1
kind: ConfigMap
metadata:
  name: alloy-config
  namespace: default
data:
  config.alloy: |
    logging {
      level  = "info"
      format = "logfmt"
    }

    discovery.kubernetes "pods" {
      role = "pod"
    }

    discovery.relabel "filtered" {
      targets = discovery.kubernetes.pods.targets

      rule {
        source_labels = ["__meta_kubernetes_namespace"]
        regex         = "default"
        action        = "keep"
      }

      rule {
        source_labels = ["__meta_kubernetes_pod_label_logging"]
        regex         = "off"
        action        = "drop"
      }

      rule {
        source_labels = ["__meta_kubernetes_pod_label_app"]
        target_label  = "service_name"
        action        = "replace"
      }

      rule {
        source_labels = ["__meta_kubernetes_namespace"]
        target_label  = "namespace"
        action        = "replace"
      }

      rule {
        source_labels = ["__meta_kubernetes_pod_name"]
        target_label  = "pod"
        action        = "replace"
      }

      rule {
        source_labels = ["__meta_kubernetes_container_name"]
        target_label  = "container"
        action        = "replace"
      }
    }

    loki.source.kubernetes "pods" {
      targets    = discovery.kubernetes.pods.targets
      forward_to = [loki.process.k8s.receiver]
    }

    loki.process "k8s" {
      forward_to = [loki.write.local.receiver]
      targets    = loki.source.kubernetes.pods.targets

      stage.docker {}
      stage.template {
        source   = "log"
        template = "[{{ printf \"%16s\" .service_name }}] {{ .Value }}"
      }
    }

    loki.write "local" {
      endpoint {
        url = "http://loki:3100/loki/api/v1/push"
      }
    }
