apiVersion: apps/v1
kind: Deployment
metadata:
  name: loki
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: loki
  template:
    metadata:
      labels:
        app: loki
        logging: "off"
    spec:
      securityContext:
        fsGroup: 10001
      serviceAccountName: default
      initContainers:
        - name: fs-perm
          image: busybox
          command: ["sh", "-c", "chown -R 10001:10001 /var/loki"]
          volumeMounts:
            - mountPath: /var/loki
              name: loki-data
      containers:
        - name: loki
          image: grafana/loki:3.5
          ports:
            - name: api
              containerPort: 3100
            - name: client
              containerPort: 7946
          args:
            [
              "-config.file=/etc/loki/config.yaml",
              "-target=all",
              "-legacy-read-mode=false",
            ]
          volumeMounts:
            - mountPath: /var/loki
              name: loki-data
            - mountPath: /etc/loki
              name: config
          resources:
            limits:
              cpu: 150m
              memory: 512Mi
            requests:
              cpu: 150m
              memory: 512Mi
          readinessProbe:
            httpGet:
              path: /ready
              port: 3100
            initialDelaySeconds: 5
            periodSeconds: 5
            timeoutSeconds: 5
            failureThreshold: 3
      volumes:
        - name: loki-data
          persistentVolumeClaim:
            claimName: loki-data-pvc
        - name: config
          configMap:
            name: loki-config
