apiVersion: v1
kind: PersistentVolume
metadata:
  name: rmq-pv
spec:
  storageClassName: local-path
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /var/hide/rmq
    type: DirectoryOrCreate
  persistentVolumeReclaimPolicy: Retain
