apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notification
  template:
    metadata:
      labels:
        app: notification
    spec:
      containers:
        - name: notification
          image: hideregistry.azurecr.io/hide-server-notification:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          env:
            - name: NODE_ENV
              value: production
            - name: SERVICE_PORT
              value: "80"
            - name: RMQ_URL
              value: "amqp://rabbitmq:5672"
            - name: REDIS_HOST
              value: redis
            - name: REDIS_PORT
              value: "6379"
            - name: FIREBASE_APP_ID
              value: hide-43a4b
            - name: FIREBASE_KEY_BASE64
              valueFrom:
                secretKeyRef:
                  name: hide-secrets
                  key: FIREBASE_KEY_BASE64
          readinessProbe:
            httpGet:
              path: /api/health
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 5
            timeoutSeconds: 5
            failureThreshold: 3
          resources:
            limits:
              cpu: 100m
              memory: 256Mi
            requests:
              cpu: 100m
              memory: 256Mi
      imagePullSecrets:
        - name: acr-secret
