apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notification
  template:
    metadata:
      labels:
        app: notification
    spec:
      containers:
        - name: notification
          image: hideregistry.azurecr.io/hide-server-notification:latest
          # imagePullPolicy: Never
          ports:
            - containerPort: 80
          env:
            - name: NODE_ENV
              value: production
            - name: SERVICE_PORT
              value: '80'
            - name: RMQ_URL
              value: 'amqp://rabbitmq:5672'
            - name: REDIS_HOST
              value: redis
            - name: REDIS_PORT
              value: '6379'
            - name: FIREBASE_APP_ID
              value: hide-43a4b
            - name: FIREBASE_KEY_BASE64
              valueFrom:
                secretKeyRef:
                  name: firebase-key
                  key: HIDE_FIREBASE_ADMIN_KEY_BASE64
      imagePullSecrets:
        - name: acr-secret
      initContainers:
        - name: init-redis
          image: busybox:1.28
          command:
            [
              'sh',
              '-c',
              'until nslookup redis.default.svc.cluster.local; do echo waiting for redis; sleep 2; done',
            ]
        - name: init-rmq
          image: busybox:1.28
          command:
            [
              'sh',
              '-c',
              'until nslookup rabbitmq.default.svc.cluster.local; do echo waiting for rabbitmq; sleep 2; done',
            ]
