services:
  auth:
    ports:
      - 8080:8080
    build:
      context: ../
      dockerfile: auth/dockerfile
      target: production
    image: hide-server-auth-release
    environment:
      - JAVA_OPTS: "-Xms256m -Xmx512m"
      - SPRING_PROFILES_ACTIVE: prod
    command: java -jar app.jar
