services:
  auth:
    expose:
      - 80
    build:
      context: ../
      dockerfile: auth/dockerfile
      target: development
    image: hide-server-auth
    volumes:
      - ./src:/app/src
      - /app/build
    environment:
      JAVA_OPTS: "-Xms256m -Xmx256m"
      SPRING_PROFILES_ACTIVE: local
      FIREBASE_AUTH_EMULATOR_HOST: "host.docker.internal:9099"
      AZURE_COMM_EMAIL_CONNECTION: "${AZURE_COMM_EMAIL_CONNECTION}"
      AZURE_COMM_EMAIL_USERNAME: "${AZURE_COMM_EMAIL_USERNAME}"
      AZURE_CS_SMTP_SECRET: "${AZURE_CS_SMTP_SECRET}"
      REDIS_HOST: "redis"
      REDIS_PORT: "6379"
