FROM gradle:8.12.1-jdk23 AS deps
WORKDIR /app

COPY auth/gradle ./gradle
COPY auth/gradlew .
COPY auth/build.gradle auth/settings.gradle ./
RUN chmod +x gradlew
RUN gradle dependencies --no-daemon || return 0

FROM gradle:8.12.1-jdk23 AS build
WORKDIR /app

COPY --from=deps /root/.gradle /root/.gradle
COPY auth .
RUN gradle bootJar --no-daemon

FROM gradle:8.12.1-jdk23 AS development
WORKDIR /app

COPY auth .
RUN chmod +x gradlew
CMD ["gradle", "bootRun", "--no-daemon"]

FROM eclipse-temurin:24-jre-alpine AS production
WORKDIR /app
COPY --from=build /app/build/libs/*.jar app.jar

EXPOSE 80
ENTRYPOINT ["java", "-jar", "app.jar"]
