apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yml
  - clusterissuer.yml
  - secret.yml
  - provisioner.role.yml
  - workspace.role.yml
  - alloy.role.yml
  - daemonset.yml
