apiVersion: v1
kind: Secret
metadata:
  name: hide-secrets
type: Opaque
stringData:
  FIREBASE_KEY_BASE64: "${FIREBASE_KEY_BASE64}"
  POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
  TYPESENSE_API_KEY: "${TYPESENSE_API_KEY}"
  WORKSPACE_SERVICE_SECRET: "${WORKSPACE_SERVICE_SECRET}"
  AZURE_COMM_EMAIL_CONNECTION: "${AZURE_COMM_EMAIL_CONNECTION}"
  AZURE_COMM_EMAIL_USERNAME: '${AZURE_COMM_EMAIL_USERNAME}'
  AZURE_CS_SMTP_SECRET: "${AZURE_CS_SMTP_SECRET}"
  JWT_PUBLIC_KEY: "${JWT_PUBLIC_KEY}"
  GRAFANA_GITHUB_CLIENT_ID: "${GRAFANA_GITHUB_CLIENT_ID}"
  GRAFANA_GITHUB_CLIENT_SECRET: "${GRAFANA_GITHUB_CLIENT_SECRET}"

---
apiVersion: v1
kind: Secret
metadata:
  name: acr-secret
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: "${ACR_KEY_BASE64}"
