apiVersion: apps/v1
kind: Deployment
metadata:
  name: nats
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nats
  template:
    metadata:
      labels:
        app: nats
    spec:
      containers:
        - name: nats
          image: nats:2.11.10-alpine
          ports:
            - name: client
              containerPort: 4222
            - name: cluster
              containerPort: 6222
            - name: management
              containerPort: 8222
          volumeMounts:
            - mountPath: /data
              name: nats-data
          resources:
            limits:
              cpu: 250m
              memory: 256Mi
            requests:
              cpu: 250m
              memory: 256Mi
          readinessProbe:
            tcpSocket:
              port: 4222
            initialDelaySeconds: 5
            periodSeconds: 5
            timeoutSeconds: 5
            failureThreshold: 3
      volumes:
        - name: nats-data
          persistentVolumeClaim:
            claimName: nats-pvc
