services:
  rabbitmq:
    image: rabbitmq:management-alpine
    container_name: rabbitmq
    expose:
      - 5672
    ports:
      - 15672:15672
    volumes:
      - ./.rabbitmq-data:/var/lib/rabbitmq
    deploy:
      resources:
        limits:
          cpus: "0.6"
          memory: 0.5g
        reservations:
          cpus: "0.6"
          memory: 0.5g
