spring.application.name=auth
server.port=80
spring.mvc.servlet.load-on-startup=1
azure.communication.email.connection-string=${HIDE_AZURE_COMM_EMAIL_CONNECTION}
spring.mail.host=smtp.azurecomm.net
spring.mail.port=587
spring.mail.username=hide-cs.b1846674-5c25-435d-ac57-29f0e6fc9347.896b3c55-40cc-4c30-8c76-58463b5d0196
spring.mail.password=${HIDE_AZURE_CS_SMTP_SECRET}
spring.mail.properties.mail.smtp.starttls.enable=true
redis.host=${REDIS_HOST}
redis.port=${REDIS_PORT}