services:
  service-registry:
    extends:
      file: docker-compose.yml
      service: service-registry
    environment:
      JAVA_OPTS: "-Xms256m -Xmx512m"
    build:
      context: .
      target: development
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8761/actuator/health" ]
      interval: 15s
      retries: 10
      start_period: 60s
      timeout: 10s
    volumes:
      - .:/app
      - /app/build
    command: ./gradlew bootRun --no-daemon
    restart: unless-stopped
