services:
  service-registry:
    extends:
      file: docker-compose.yml
      service: service-registry
    build:
      context: .
      target: production
    ports:
      - "8761:8761"
    restart: unless-stopped
