FROM golang:1.24-bookworm AS build
WORKDIR /app
COPY go.mod go.mod
COPY go.sum go.sum
RUN go mod download
COPY . .
RUN CGO_ENABLED=0 GOOS=linux go build -a -o manager cmd/main.go

FROM gcr.io/distroless/static:nonroot  AS production
WORKDIR /
COPY --from=build /app/manager .
USER 65532:65532

ENTRYPOINT ["/manager"]
