apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: auth
    spec:
      containers:
        - name: auth
          image: hideregistry.azurecr.io/hide-server-env:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          env:
            - name: JAVA_OPTS
              value: "-Xms256m -Xmx512m"
            - name: SPRING_PROFILES_ACTIVE
              value: "prod"
            - name: REDIS_HOST
              value: "redis"
            - name: REDIS_PORT
              value: "6379"
            - name: FIREBASE_KEY_BASE64
              valueFrom:
                secretKeyRef:
                  name: hide-secrets
                  key: FIREBASE_KEY_BASE64
            - name: AZURE_COMM_EMAIL_CONNECTION
              valueFrom:
                secretKeyRef:
                  name: hide-secrets
                  key: AZURE_COMM_EMAIL_CONNECTION
            - name: AZURE_CS_SMTP_SECRET
              valueFrom:
                secretKeyRef:
                  name: hide-secrets
                  key: AZURE_CS_SMTP_SECRET
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 5
            timeoutSeconds: 5
            failureThreshold: 3
          resources:
            requests:
              cpu: "500m"
              memory: "500M"
            limits:
              cpu: "500m"
              memory: "500M"
      imagePullSecrets:
        - name: acr-secret
