services:
  notification:
    ports:
      - 3004:3004
    build:
      context: ../
      dockerfile: notification/dockerfile
      target: development
    image: hide-server-notification
    volumes:
      - .:/app/notification
      - /app/notification/node_modules
    environment:
      - NODE_ENV=development
      - SERVICE_PORT=3004
      - RMQ_URL=amqp://rabbitmq:5672
      - FIREBASE_EMULATION=true
      - FIREBASE_AUTH_EMULATOR_HOST=host.docker.internal:9099
      - FIRESTORE_EMULATOR_HOST=host.docker.internal:8085
      - FIREBASE_STORAGE_EMULATOR_HOST=host.docker.internal:9199
      - FIREBASE_APP_ID=hide-43a4b
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    command: [ "/bin/sh", "-c", "cd notification && npm run start:dev" ]
