FROM node:22-alpine AS base
RUN apk add jq
WORKDIR /app

FROM base AS development
COPY notification ./notification
COPY libs ./libs
RUN cd ./notification && npm ci
RUN for dir in $(jq ".references[].path" ./notification/tsconfig.json); do \
  (cd "${dir:2:-1}" && npm ci); \
  done
CMD ["/bin/sh", "-c", "cd notification && npm run start:dev"]

FROM base AS build
COPY notification ./notification
COPY libs ./libs
RUN cd ./notification && npm ci
RUN for dir in $(jq ".references[].path" ./notification/tsconfig.json); do \
  (cd "${dir:2:-1}" && npm ci); \
  done
RUN npm run build --prefix notification

FROM base AS production
COPY --from=build /app/notification/dist ./notification/dist
COPY --from=build /app/notification/package.json ./notification/package.json
COPY --from=build /app/notification/package-lock.json ./notification/package-lock.json
COPY --from=build /app/notification/node_modules ./notification/node_modules
COPY --from=build /app/libs ./libs
CMD ["/bin/sh", "-c", "cd notification && npm run start:prod"]

EXPOSE 80