services:
  notification:
    expose:
      - 80
    build:
      context: ../
      dockerfile: notification/dockerfile
      target: development
    image: hide-server-notification
    volumes:
      - ./src:/app/notification/src
      - /app/notification/node_modules
    environment:
      - NODE_ENV=development
      - SERVICE_PORT=80
      - RMQ_URL=amqp://rabbitmq:5672
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - FIREBASE_APP_ID=hide-43a4b
      - FIREBASE_EMULATION=true
      - FIREBASE_AUTH_EMULATOR_HOST=host.docker.internal:9099
      - FIRESTORE_EMULATOR_HOST=host.docker.internal:8085
      - FIREBASE_STORAGE_EMULATOR_HOST=host.docker.internal:9199
