services:
  notification:
    extends:
      file: docker-compose.yml
      service: notification
    build:
      context: .
      target: production
    environment:
      - EUREKA_HOST=host.docker.internal
      - EUREKA_PORT=8761
      - SERVICE_NAME=NOTIFICATION
      - SERVICE_PORT=3004
    command: node dist/main.js
