apiVersion: apps/v1
kind: Deployment
metadata:
  name: lease-controller-deployment
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lease-controller
  template:
    metadata:
      labels:
        app: lease-controller
    spec:
      serviceAccountName: controller-manager
      containers:
        - name: manager
          image: hideregistry.azurecr.io/hide-server-lease-controller:latest
          imagePullPolicy: Always
          ports: []
          command:
            - /manager
          args:
            - --health-probe-bind-address=:8081
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8081
            initialDelaySeconds: 15
            periodSeconds: 20
          readinessProbe:
            httpGet:
              path: /readyz
              port: 8081
            initialDelaySeconds: 5
            periodSeconds: 10
          resources:
            limits:
              cpu: 75m
              memory: 200Mi
            requests:
              cpu: 75m
              memory: 200Mi
      imagePullSecrets:
        - name: acr-secret
