root = "."
tmp_dir = "tmp"

[build]
cmd = "go build -o ./.build/main ."
bin = "./.build/main"
include_ext = ["go"]
# Ignore these filename extensions or directories.
exclude_dir = [".build"]
exclude_regex = ["_test\\.go"]
exclude_unchanged = true
follow_symlink = true
log = "air.log"
rerun_delay = 500

[log]
time = true
main_only = false
silent = false

[color]
main = "magenta"
watcher = "cyan"
build = "yellow"
runner = "green"

[misc]
clean_on_exit = true

[screen]
clear_on_rebuild = true
keep_scroll = true

# [proxy]
# enabled = true
# proxy_port = 8090
# app_port = 8080
