services:
  provisioner:
    expose:
      - 80
    build:
      context: ../
      dockerfile: provisioner/dockerfile
      target: development
    image: hide-server-provisioner
    volumes:
      - .:/app
      - /app/.build
    environment:
      SERVICE_PORT: 80
      REDIS_HOST: redis
      REDIS_PORT: 6379
      NATS_URL: nats://nats:4222
      K8S_API_SERVER: https://kubernetes.docker.internal:6443
      DOCKER_HOST: tcp://host.docker.internal:2375
      DEV_PLATFORM: docker
      DEV_FS_SOURCE: "${DEV_FS_SOURCE}"
      WORKSPACE_CPU_REQUEST: "200"
      IDLE_THRESHOLD_CPU: "350"
      PREEMPT_SPOT_OLDER_THAN_HOURS: "12"
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: 512m
