FROM golang:1.24 AS builder
WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN CGO_ENABLED=0 GOOS=linux go build -o ./.build/main .

FROM golang:1.24 AS development
WORKDIR /app
RUN go install github.com/air-verse/air@latest
COPY . .
CMD ["air", "-c", ".air.toml"]

FROM alpine:latest AS production
WORKDIR /app
COPY --from=builder /app/.build/main .
RUN chmod +x main
EXPOSE 8080
CMD ["./main"]
