services:
  provisioner:
    ports:
      - 3005:3005
    build:
      context: .
      dockerfile: dockerfile
      target: development
    image: hide-server-provisioner
    volumes:
      - .:/app
      - ~/.kube:/root/.kube
      - /app/.build
    environment:
      - SERVICE_PORT=3005
      - K8S_API_SERVER=https://host.docker.internal:6443
    command: [ "/bin/sh", "-c", "air -c .air.toml" ]
