apiVersion: apps/v1
kind: Deployment
metadata:
  name: user
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user
  template:
    metadata:
      labels:
        app: user
    spec:
      containers:
        - name: user
          image: hideregistry.azurecr.io/hide-server-user:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          env:
            - name: NODE_ENV
              value: production
            - name: SERVICE_PORT
              value: "80"
            - name: FIREBASE_APP_ID
              value: "hide-43a4b"
            - name: TYPESENSE_HOST
              value: "typesense"
            - name: TYPESENSE_PORT
              value: "8108"
            - name: TYPESENSE_PROTOCOL
              value: "http"
            - name: REDIS_HOST
              value: "redis"
            - name: REDIS_PORT
              value: "6379"
            - name: NATS_URL
              value: nats://nats:4222
            - name: RMQ_URL
              value: "amqp://rabbitmq:5672"
            - name: GUEST_ACCOUNT_EXPIRY_DAYS
              value: "2"
            - name: FIREBASE_KEY_BASE64
              valueFrom:
                secretKeyRef:
                  name: hide-secrets
                  key: FIREBASE_KEY_BASE64
            - name: TYPESENSE_API_KEY
              valueFrom:
                secretKeyRef:
                  name: hide-secrets
                  key: TYPESENSE_API_KEY
          readinessProbe:
            httpGet:
              path: /api/health
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 5
            timeoutSeconds: 5
            failureThreshold: 3
          resources:
            limits:
              cpu: 100m
              memory: 200Mi
            requests:
              cpu: 100m
              memory: 200Mi
      imagePullSecrets:
        - name: acr-secret
