FROM node:22-alpine AS base
RUN apk add jq
WORKDIR /app

FROM base AS development
COPY user ./user
COPY libs ./libs
RUN cd ./user && npm ci
RUN for dir in $(jq ".references[].path" ./user/tsconfig.json); do \
  (cd "${dir:2:-1}" && npm ci); \
  done
CMD ["/bin/sh", "-c", "cd user && npm run start:dev"]

FROM base AS build
COPY user ./user
COPY libs ./libs
RUN cd ./user && npm ci
RUN for dir in $(jq ".references[].path" ./user/tsconfig.json); do \
  (cd "${dir:2:-1}" && npm ci); \
  done
RUN npm run build --prefix user

FROM base AS production
COPY --from=build /app/user/dist ./user/dist
COPY --from=build /app/user/package.json ./user/package.json
COPY --from=build /app/user/package-lock.json ./user/package-lock.json
COPY --from=build /app/user/node_modules ./user/node_modules
COPY --from=build /app/libs ./libs
CMD ["/bin/sh", "-c", "cd user && npm run start:prod"]

EXPOSE 80