FROM node:22-alpine AS base
WORKDIR /app
RUN apk add --no-cache jq

FROM base AS development
COPY user ./user
COPY libs ./libs  
WORKDIR /app/user
RUN npm ci
RUN for dir in $(jq -r ".references[].path" tsconfig.json); do \
  (cd "$dir" && npm ci); \
  done
CMD ["npm", "run", "start:dev"]

FROM base AS build
COPY user ./user
COPY libs ./libs
WORKDIR /app/user
RUN npm ci
RUN for dir in $(jq -r ".references[].path" tsconfig.json); do \
  cd "/app/${dir#../}" && \
  npm ci && \
  npm run build && \
  npm pack; \
  done
WORKDIR /app/user
RUN for dir in $(jq -r ".references[].path" tsconfig.json); do \
  clean_dir=${dir#../}; \
  tarball=$(ls /app/$clean_dir/*.tgz); \
  pkg=$(jq -r .name /app/$clean_dir/package.json); \
  jq ".dependencies[\"$pkg\"] = \"$tarball\"" package.json > package.json.tmp && mv package.json.tmp package.json; \
  done
RUN npm run build
RUN rm -rf node_modules package-lock.json && npm install --omit=dev

FROM node:22-alpine AS production
WORKDIR /app
COPY --from=build /app/user/node_modules ./user/node_modules
COPY --from=build /app/user/dist ./user/dist
COPY --from=build /app/user/package*.json ./user/

EXPOSE 80
CMD ["node", "user/dist/main.js"]
