FROM node:20-alpine AS base
RUN apk add jq
WORKDIR /app

FROM base AS development
COPY user ./user
COPY libs ./libs
RUN cd ./user && npm ci
# RUN cd ./libs/eureka && npm ci
# RUN cd ./libs/firebase && npm ci
RUN for dir in $(jq ".references[].path" ./user/tsconfig.json); do \
  (cd "${dir:2:-1}" && npm ci); \
  done
CMD ["cd", "user", "&&", "npm", "run", "start:dev"]

FROM base AS production
RUN npm ci --omit=dev
COPY user ./user
COPY libs ./libs
RUN cd ./libs/eureka && npm ci
RUN cd ./libs/firebase && npm ci
RUN npm run build
CMD ["node", "dist/main.js"]
