services:
  env:
    expose:
      - 80
    build:
      context: ../
      dockerfile: env/dockerfile
      target: development
    image: hide-server-env
    volumes:
      - ./src:/app/env/src
      - /app/env/node_modules
    environment:
      - NODE_ENV=development
      - SERVICE_PORT=80
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - RMQ_URL=amqp://rabbitmq:5672
      - NATS_URL=nats://nats:4222
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512m
