services:
  redis:
    image: redis:alpine
    container_name: redis
    expose:
      - 6379
    command: ["redis-server", "--notify-keyspace-events", "Ex"]
    deploy:
      resources:
        limits:
          cpus: "0.4"
          memory: 0.3g
        reservations:
          cpus: "0.4"
          memory: 0.3g
