name: Build

on:
  workflow_dispatch:
    inputs:
      services:
        description: "Comma-separated list of services to build (gateway, env, user, notification, workspace, auth, provisioner). Leave blank to use paths-filter."
        required: false
        default: ""
  push:
    branches:
      - main
    paths:
      - "gateway/**"
      - "env/**"
      - "user/**"
      - "notification/**"
      - "workspace/**"
      - "auth/**"
      - "provisioner/**"
      - "!gateway/k8s/**"
      - "!env/k8s/**"
      - "!user/k8s/**"
      - "!notification/k8s/**"
      - "!workspace/k8s/**"
      - "!auth/k8s/**"
      - "!provisioner/k8s/**"

jobs:
  changes:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.filter.outputs.changes }}
    steps:
      - uses: actions/checkout@v4
      - uses: dorny/paths-filter@v3
        name: Filter
        id: filter
        with:
          filters: |
            gateway:
              - 'gateway/**'
            env:
              - 'env/**'
            user:
              - 'user/**'
            notification:
              - 'notification/**'
            workspace:
              - 'workspace/**'
            auth:
              - 'auth/**'
            provisioner:
              - 'provisioner/**'

  prepare:
    needs: changes
    runs-on: ubuntu-latest
    outputs:
      services: ${{ steps.set-matrix.outputs.services }}
    steps:
      - id: set-matrix
        run: |
          if [[ "${{ github.event_name }}" == "workflow_dispatch" ]]; then
            input="${{ github.event.inputs.services }}"
            json=$(jq -nc --arg input "$input" '$input | split(",")')
            echo "services=$json" >> $GITHUB_OUTPUT
          else
            echo 'services=${{ needs.changes.outputs.matrix }}' >> $GITHUB_OUTPUT
          fi

  build:
    needs: [changes, prepare]
    runs-on: ubuntu-24.04-arm
    strategy:
      matrix:
        service: ${{ fromJSON(needs.prepare.outputs.services) }}
    steps:
      - uses: actions/checkout@v4

      - name: Azure Service Principal Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Build and push image
        uses: azure/docker-login@v2
        with:
          login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
      - run: |
          IMAGE=${{ secrets.REGISTRY_LOGIN_SERVER }}/hide-server-${{ matrix.service }}:latest
          cd ${{ matrix.service }}
          docker buildx build --platform linux/arm64 --target production -f dockerfile -t $IMAGE --push ..
