services:
  workspace:
    expose:
      - 80
    build:
      context: ../
      dockerfile: workspace/dockerfile
      target: development
    volumes:
      - ./src:/app/workspace/src
      - /app/workspace/node_modules
    environment:
      NODE_ENV: development
      SERVICE_PORT: 80
      RMQ_URL: 'amqp://rabbitmq:5672'
      REDIS_HOST: redis
      REDIS_PORT: 6379
      NATS_URL: 'nats://nats:4222'
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: workspacedb
      WORKSPACE_SERVICE_SECRET: ${WORKSPACE_SERVICE_SECRET}
      FIREBASE_EMULATION: true
      FIREBASE_AUTH_EMULATOR_HOST: host.docker.internal:9099
      FIRESTORE_EMULATOR_HOST: host.docker.internal:8085
      FIREBASE_STORAGE_EMULATOR_HOST: host.docker.internal:9199
      FIREBASE_APP_ID: hide-43a4b
      WORKSPACE_CREATION_LIMIT_GUEST: 1
      WORKSPACE_CREATION_LIMIT_NON_GUEST: 2
      AZURE_COMM_EMAIL_CONNECTION: '${AZURE_COMM_EMAIL_CONNECTION}'
      AZURE_CS_SMTP_SECRET: '${AZURE_CS_SMTP_SECRET}'
      AZURE_COMM_EMAIL_USERNAME: '${AZURE_COMM_EMAIL_USERNAME}'
      ADMIN_EMAIL: 'support.hide@saurabhagat.me'
      WEBHOOK_URL: 'http://localhost:3001/api'
      WORKSPACE_CPU_REQUEST: '200'
      IDLE_THRESHOLD_CPU: '350'
      DEV_PLATFORM_SIMULATE: docker,true
      ACCESS_CODE_EXPIRY_DAYS: '5'
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1.5g
