services:
  workspace:
    ports:
      - 3003:3003
    build:
      context: ../
      dockerfile: workspace/dockerfile
      target: development
    volumes:
      - .:/app/workspace
      - /app/workspace/node_modules
    environment:
      - NODE_ENV=development
      - SERVICE_PORT=3003
      - RMQ_URL=amqp://rabbitmq:5672
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_USER=admin
      - POSTGRES_PASS=${POSTGRES_PASS}
      - POSTGRES_DB=workspacedb
      - WORKSPACE_SERVICE_SECRET=${WORKSPACE_SERVICE_SECRET}
    command: [ "/bin/sh", "-c", "cd workspace && npm run start:dev" ]
