FROM node:20-alpine AS base
RUN apk add jq
WORKDIR /app

FROM base AS development
COPY workspace ./workspace
COPY libs ./libs
RUN cd ./workspace && npm ci
RUN for dir in $(jq ".references[].path" ./workspace/tsconfig.json); do \
  (cd "${dir:2:-1}" && npm ci); \
  done
CMD ["/bin/sh", "-c", "cd workspace && npm run start:dev"]

FROM base AS builder
COPY workspace ./workspace
COPY libs ./libs
RUN cd ./workspace && npm ci
RUN for dir in $(jq ".references[].path" ./workspace/tsconfig.json); do \
  (cd "${dir:2:-1}" && npm ci); \
  done
RUN npm run build --prefix workspace

FROM base AS production
COPY --from=builder /app/workspace/dist ./workspace/dist
COPY --from=builder /app/workspace/package.json ./workspace/package.json
COPY --from=builder /app/workspace/package-lock.json ./workspace/package-lock.json
COPY --from=builder /app/workspace/node_modules ./workspace/node_modules
COPY --from=builder /app/libs ./libs
CMD ["/bin/sh", "-c", "cd workspace && npm run start:prod"]
