services:
  workspace:
    extends:
      file: docker-compose.yml
      service: workspace
    build:
      context: .
      target: production
    environment:
      - EUREKA_HOST=host.docker.internal
      - EUREKA_PORT=8761
      - SERVICE_NAME=WORKSPACE
      - SERVICE_PORT=3003
    command: node dist/main.js
